### ISSUE TITLE
Default letter spacing 2

### ISSUE THREAD

**Issue by antonk52** [wtanna/Spacegray-OSX-Terminal-Theme#1]
By default letter spacing is set to 2. Can be fixed by chaging on lines 166-176 to 

```
<key>Font</key>
<data>
YnBsaXN0MDDUAQIDBAUGGBlYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3AS
AAGGoKQHCBESVSRudWxs1AkKCwwNDg8QVk5TU2l6ZVhOU2ZGbGFnc1ZOU05hbWVWJGNs
YXNzI0AsAAAAAAAAEBCAAoADXURyb2lkU2Fuc01vbm/SExQVFlokY2xhc3NuYW1lWCRj
bGFzc2VzVk5TRm9udKIVF1hOU09iamVjdF8QD05TS2V5ZWRBcmNoaXZlctEaG1Ryb290
gAEIERojLTI3PEJLUltiaXJ0dniGi5afpqmyxMfMAAAAAAAAAQEAAAAAAAAAHAAAAAAA
AAAAAAAAAAAAAM4=
</data>
<key>FontAntialias</key>
<true/>
<key>FontWidthSpacing</key>
<real>1.004032258064516</real>
<key>Linewrap</key>
<true/>
```

You can also see example of this in my [fork](https://github.com/antonk52/Spacegray-OSX-Terminal-Theme).

**Comment by wtanna** [comment]
I went ahead and set the default font to one that is a standard across different versions of OSX. On a clean install of High Sierra installing this theme uses `Courier New` and uses the default width spacing. Going to close this now since there shouldn't be any weird font issues now.
